# Generated by Django 4.2.1 on 2023-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=18)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
