# Generated by Django 4.2.1 on 2023-07-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_rename_file_employee_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='file',
            new_name='File',
        ),
    ]
